// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPGGg6erpWZJ3IJ9Xv_22JPaScHkw-9fE',
    appId: '1:184439242757:web:faed5aa783336ab1b51c6c',
    messagingSenderId: '184439242757',
    projectId: 'foodapp-44890',
    authDomain: 'foodapp-44890.firebaseapp.com',
    storageBucket: 'foodapp-44890.firebasestorage.app',
    measurementId: 'G-6RLBLPWCGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBucM1sPZdoA7QVnQqrG2zfqeUZBw6Kh64',
    appId: '1:184439242757:android:1dd86383eab87fd6b51c6c',
    messagingSenderId: '184439242757',
    projectId: 'foodapp-44890',
    storageBucket: 'foodapp-44890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZfRE32ZJAYmGiJRVzwXPGiuZ-kyet0l4',
    appId: '1:184439242757:ios:43719f99109a1925b51c6c',
    messagingSenderId: '184439242757',
    projectId: 'foodapp-44890',
    storageBucket: 'foodapp-44890.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZfRE32ZJAYmGiJRVzwXPGiuZ-kyet0l4',
    appId: '1:184439242757:ios:43719f99109a1925b51c6c',
    messagingSenderId: '184439242757',
    projectId: 'foodapp-44890',
    storageBucket: 'foodapp-44890.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPGGg6erpWZJ3IJ9Xv_22JPaScHkw-9fE',
    appId: '1:184439242757:web:ceb076ae6a380108b51c6c',
    messagingSenderId: '184439242757',
    projectId: 'foodapp-44890',
    authDomain: 'foodapp-44890.firebaseapp.com',
    storageBucket: 'foodapp-44890.firebasestorage.app',
    measurementId: 'G-T35BV20KGK',
  );
}
