import 'dart:io';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:food_recipe_app/model/comment_model.dart';
import 'package:food_recipe_app/model/cookbook_model.dart';
import 'package:food_recipe_app/model/food_model.dart';
import 'package:food_recipe_app/model/user_model.dart';
import 'package:food_recipe_app/views/auth/change_password.dart';
import 'package:food_recipe_app/views/auth/forgot_password.dart';
import 'package:food_recipe_app/views/auth/login.dart';
import 'package:food_recipe_app/views/auth/register.dart';
import 'package:food_recipe_app/views/main/add_edit_food/search_page.dart';
import 'package:food_recipe_app/views/main/categories/food_list_with_tag.dart';
import 'package:food_recipe_app/views/main/cookbook/pages/add_cookbook_page.dart';
import 'package:food_recipe_app/views/main/cookbook/pages/cookbook_detail.dart';
import 'package:food_recipe_app/views/main/cookbook/pages/cookbook_screen.dart';
import 'package:food_recipe_app/views/main/cookbook/pages/cookbook_selection.dart';
import 'package:food_recipe_app/views/main/cookbook/pages/edit_cookbook_page.dart';
import 'package:food_recipe_app/views/main/food_details/food_screen/all_food_by_date.dart';
import 'package:food_recipe_app/views/main/food_details/user_interaction/resources/comment_page.dart';
import 'package:food_recipe_app/views/main/food_details/user_interaction/resources/reply_comment_page.dart';
import 'package:food_recipe_app/views/main/food_storage/my_food.dart';
import 'package:food_recipe_app/views/main/food_storage/recent_view.dart';
import 'package:food_recipe_app/views/main/food_storage/save_food.dart';
import 'package:food_recipe_app/views/main/food_storage/storage_mode_select.dart';
import 'package:food_recipe_app/views/main/notification/notification_screen.dart';
import 'package:food_recipe_app/views/main/report/my_report_page.dart';
import 'package:food_recipe_app/views/main/settings/settings_screen.dart';
import 'package:food_recipe_app/views/main/sub_features/about/about_screen.dart';
import 'package:food_recipe_app/views/main/add_edit_food/add_food_screen.dart';
import 'package:food_recipe_app/views/main/add_edit_food/edit_food_screen.dart';
import 'package:food_recipe_app/views/main/categories/categories_page.dart';
import 'package:food_recipe_app/views/main/food_details/food_screen/all_list_food.dart';
import 'package:food_recipe_app/views/main/food_details/food_screen/food_detail_page.dart';
import 'package:food_recipe_app/views/main/food_storage/storage_view.dart';
import 'package:food_recipe_app/views/main/home/home_screen.dart';
import 'package:food_recipe_app/views/main/main_page.dart';
import 'package:food_recipe_app/views/main/sub_features/about/app_overview.dart';
import 'package:food_recipe_app/views/main/sub_features/about/contact.dart';
import 'package:food_recipe_app/views/main/sub_features/theme/change_theme_screen.dart';
import 'package:food_recipe_app/views/main/user/delete_user_screen.dart';
import 'package:food_recipe_app/views/main/user/edit_user.dart';
import 'package:food_recipe_app/views/main/user/personal_screen.dart';
import 'package:food_recipe_app/views/main/user/user_information.dart';
import 'package:food_recipe_app/views/start/internet_check.dart';
import 'package:food_recipe_app/views/start/onboard.dart';
import 'package:food_recipe_app/views/start/splash_screen.dart';

//routes
Route materialRoute(Widget page) => MaterialPageRoute(builder: (context) => page);
Route cupertinoRoute(Widget page) => CupertinoPageRoute(builder: (context) => page);
Route checkDeviceRoute(Widget page) => Platform.isAndroid ? materialRoute(page) : cupertinoRoute(page);

//pages
Widget get loginPage => Login();
Widget get registerPage => Register();
Widget get forgotPasswordPage => ForgotPassword();
Widget get changePasswordPage => ChangePassword();
Widget get splashScreen => SplashScreen();
Widget get mainPage => MainPage();
Widget get internetCheck => InternetCheck();
Widget get onboardScreen => Onboard();
Widget get homeScreen => HomeScreen();
Widget get addFood => AddFoodScreen();
Widget editFood(FoodModel food) => EditFoodScreen(food: food);
Widget commentPage(FoodModel food) => CommentPage(food: food);
Widget foodDetailPage(FoodModel food, String id, List<Map<String, dynamic>> likedList) => FoodDetailPage(food: food, id: id, likedList: likedList);
Widget userInform(UserModel user) => UserInformation(user: user);
Widget editUserPage(UserModel user) => EditUser(user: user);
Widget get categoriesPage => CategoriesPage();
Widget get foodStorageView => StorageView();
Widget personalScreen(String id) => PersonalScreen(id: id);
Widget get listofFoodView => AllListFood();
Widget get about => AboutScreen();
Widget get changeThemeScreen => ChangeThemeScreen();
Widget get settings => SettingsScreen();
Widget get searchPage => SearchPage();
Widget get myFoodScreen => MyFood();
Widget get saveFoodScreen => SaveFood();
Widget get recentScreen => RecentView();
Widget listofFoodByTag(String categories) => FoodListWithTag(categories: categories);
Widget listofFoodByDate(bool isDescending) => AllFoodByDate(isDescending: isDescending);
Widget get storageMode => StorageModeSelect();
Widget get deleteUser => DeleteUserScreen();
Widget get cookbookPage => CookbookScreen();
Widget cookbookSelection(FoodModel food) => CookbookSelection(food: food);
Widget cookbookDetail(CookbookModel cookbook) => CookbookDetail(cookbook: cookbook);
Widget get appoverview => AppOverview();
Widget get contactpage => Contact();
Widget get reportPage => MyReportPage();
Widget get addCookbook => AddCookbookPage();
Widget editCookbook(CookbookModel cookbook) => EditCookbookPage(cookbook: cookbook);
Widget get notification => NotificationScreen();
Widget replyPage(CommentModel comment, String id) => ReplyCommentPage(comment: comment, id: id);